#!/bin/bash

# Exit on any errors
set -e

source $OPENSHIFT_CARTRIDGE_SDK_BASH

list=
kvargs=$(echo "${@:4}" | tr -d "\n" )
for arg in $kvargs; do
    ip=$(echo "$arg" | cut -f 2 -d '=' | tr -d "'")
    if [ -z "$list" ]; then
        list="$ip"
    else
        list="$list $ip"
    fi
done

OPENSHIFT_JBOSSEWS_PROXY_IP=$(ping -c 1 ${OPENSHIFT_GEAR_DNS} | awk '{ print $3 ; exit }' | sed 's/(//g' | sed 's/)//g')
echo $OPENSHIFT_JBOSSEWS_PROXY_IP > $OPENSHIFT_JBOSSEWS_DIR/env/OPENSHIFT_JBOSSEWS_PROXY_IP

echo $list > $OPENSHIFT_JBOSSEWS_DIR/env/OPENSHIFT_JBOSSEWS_HAZELCAST_CLUSTER


